Console.WriteLine("Приветствую! ");
Console.WriteLine("Эта программа определяет какова должна быть длина шнурка для элитных ботинок");
Console.WriteLine("Обувная фабрика собирается начать выпуск элитной модели ботинок.");
Console.WriteLine("Дырочки для шнуровки будут расположены в два ряда,");
Console.WriteLine("расстояние между рядами равно a,");
Console.WriteLine("а расстояние между дырочками в ряду b.");
Console.WriteLine("Количество дырочек в каждом ряду равно N.");
Console.WriteLine("Шнуровка должна происходить элитным способом");
Console.WriteLine("наверх, по горизонтали в другой ряд, наверх, по горизонтали и т.д.");
Console.WriteLine("Кроме того, чтобы шнурки можно было завязать элитным бантиком,");
Console.WriteLine("длина свободного конца шнурка должна быть l.");
int a, b, N, l, length;
Console.WriteLine("Введите расстояние между рядами - a : ");
a = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите расстояние между дырочками в ряду - b : ");
b = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите количество дырочек в каждом ряду - N : ");
N = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите длину свободного конца шнурка - l : ");
l = Convert.ToInt32(Console.ReadLine());
length = 2*((N*a)+(N*b)+l);
Console.WriteLine("Длина шнурка для элитных ботинок : ");
Console.Write(length);